
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r 'T9/Exchange rate/requirements.txt'
    - name: Run tests
      run: |
        cd 'T9/Exchange rate'
        export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        pytest tests/